host: '127.0.0.1:8001'
headers: []
apis:
  - name: devops-canary-ui
    plugins:
      - name: acl
        attributes:
          enabled: true
          config:
            whitelist:
              - canary-users
      - name: basic-auth
        attributes:
          enabled: true
          config:
            # Do not forward the Authorization header to the upstream service.
            hide_credentials: true
            # Empty string will return a 4xx authentication error.
            anonymous: ''
    attributes:
      uris:
        - /canary
      strip_uri: true
      preserve_host: false
      upstream_url: 'https://webappcanary.devops-belfast-0.us-east-1.pdev.r7ops.com'
      retries: 5
      upstream_connect_timeout: 60000
      upstream_read_timeout: 60000
      upstream_send_timeout: 60000
      https_only: false
      http_if_terminated: true

  - name: devops-ui
    plugins: []
    attributes:
      uris:
        - /
      strip_uri: false
      preserve_host: false
      upstream_url: 'https://webapp.devops-belfast-0.us-east-1.pdev.r7ops.com'
      retries: 5
      upstream_connect_timeout: 60000
      upstream_read_timeout: 60000
      upstream_send_timeout: 60000
      https_only: false
      http_if_terminated: true

consumers:
  - username: jdoe
    acls:
      - group: beta-users
    credentials:
      - name: basic-auth
        attributes:
          password: fb1eb10b940221517967f5f48d01acecb0db4a0b
          username: jdoe
  - username: jsmith
    acls:
      - group: canary-users
    credentials:
      - name: basic-auth
        attributes:
          password: 15b6d69557d2aa0e91141f23a81ac891d713f468
          username: jsmith
plugins: []
