apis:
  - name: devops-canary-ui
    plugins:
      - name: basic-auth
        attributes:
          enabled: true
          config:
            # Do not forward the Authorization header to the upstream service.
            hide_credentials: true
            # Empty string will return a 4xx authentication error.
            anonymous: ''
    attributes:
      uris:
        - /canary
      strip_uri: true
      preserve_host: false
      upstream_url: 'https://webappcanary.devops-belfast-0.us-east-1.pdev.r7ops.com'
      retries: 5
      upstream_connect_timeout: 60000
      upstream_read_timeout: 60000
      upstream_send_timeout: 60000
      https_only: false
      http_if_terminated: true

  - name: devops-ui
    plugins: []
    attributes:
      uris:
        - /
      strip_uri: false
      preserve_host: false
      upstream_url: 'https://webapp.devops-belfast-0.us-east-1.pdev.r7ops.com'
      retries: 5
      upstream_connect_timeout: 60000
      upstream_read_timeout: 60000
      upstream_send_timeout: 60000
      https_only: false
      http_if_terminated: true

consumers:
  - username: jdoe
    credentials:
      - name: basic-auth
        attributes:
          password: 9fd10d6cca742c2666bdf137d04c0398f55f4c3e
          username: jdoe

plugins: []
